#!/bin/bash

# Turn off echo
set +x

# - rustup target list | grep ohos
# - aarch64-unknown-linux-ohos
# - armv7-unknown-linux-ohos
# - x86_64-unknown-linux-ohos
# - rustup target add aarch64-unknown-linux-ohos
# 使用默认平台编译 `rustup show active-toolchain`

cargo build --release --target aarch64-unknown-linux-ohos

# 输出目录在 ./target/aarch64-unknown-linux-ohos/release

# 编译头文件
./generate_headers